### PR TITLE
Edits primarily to intermediate document

### PR DESCRIPTION
**Pull request by baskaufs**
I see that when I created the first pull request, I did it on Heard Library instead of the @Ramona2020 fork. So I'm closing that one and opening this one.

### CODE REVIEW

**Comment by Ramona2020** [comment]
@baskaufs I'm done!  Take a look and see how things will flow into your segment.  I put in a header section  for your merge conflicts component.

**Comment by baskaufs** [comment]
Hey, Ramona, beautiful!  I haven't figured out how to merge in my stuff yet, but I'll try to get to it before tomorrow and we can touch bases again then.

**Comment by Ramona2020** [comment]
Maybe create another so you can have "space" to resolve the merge conflicts for the handouts.  Would it be easier to split the intermediate handout into two parts? Intermediate part 1 and part 2 so that we don't have "style" both parts the same.

**Comment by baskaufs** [comment]
Sure, just splitting the page would probably be the easiest thing.

**Comment by baskaufs** [comment]
abandon branch in favor of new branch

**Pull request closed without merging**
